/**
 * T-09.4: URL slug mapper
 * Maps existing file paths to ChiselGrid slugs, preserves SEO-critical URLs.
 */

import type { SlugMapping } from './types.js';

/** Generate a ChiselGrid slug from a source file path */
export function generateSlug(sourcePath: string): string {
  return sourcePath
    .replace(/\.(html|md|mmd)$/, '')
    .replace(/\/index$/, '')
    .replace(/\//g, '-')
    .replace(/[^a-z0-9-]/gi, '-')
    .replace(/-+/g, '-')
    .replace(/^-|-$/g, '')
    .toLowerCase();
}

/** Build slug mappings for all converted content */
export function buildSlugMappings(
  conversions: { sourcePath: string; slug: string; originalUrl: string }[],
): SlugMapping[] {
  return conversions.map((c) => {
    const originalUrl = c.originalUrl;
    const newUrl = `/articles/${c.slug}`;
    const redirectNeeded = originalUrl !== newUrl;

    return {
      originalPath: c.sourcePath,
      originalUrl,
      newSlug: c.slug,
      redirectNeeded,
    };
  });
}

/** Generate CloudFront function redirect code */
export function generateCloudFrontRedirects(mappings: SlugMapping[]): string {
  const redirects = mappings.filter((m) => m.redirectNeeded);

  if (redirects.length === 0) return '// No redirects needed';

  const cases = redirects
    .map(
      (m) =>
        `    '${m.originalUrl}': '/articles/${m.newSlug}',`,
    )
    .join('\n');

  return `// T-09.6: CloudFront redirect rules for migrated content
// Generated by ChiselGrid migration tool
// Deploy as CloudFront Function (viewer-request)

function handler(event) {
  var request = event.request;
  var uri = request.uri;

  var redirects = {
${cases}
  };

  if (redirects[uri]) {
    return {
      statusCode: 301,
      statusDescription: 'Moved Permanently',
      headers: {
        location: { value: redirects[uri] },
        'cache-control': { value: 'public, max-age=86400' },
      },
    };
  }

  return request;
}
`;
}
