import { DiagramType, NodeType, EdgeType, ZoneType } from './types';
import type { GridIR } from './types';

const awsArchitecture: GridIR = {
  version: '1.0',
  diagram_type: DiagramType.AWSArchitecture,
  abstraction_level: 2,
  title: 'AWS Serverless API',
  nodes: [
    {
      id: 'cloudfront',
      type: NodeType.AWSCloudFront,
      label: 'CloudFront',
      zone: 'public',
    },
    {
      id: 'api-gateway',
      type: NodeType.AWSAPIGateway,
      label: 'API Gateway',
      zone: 'public',
      properties: { protocol: 'REST', auth: 'Cognito' },
    },
    {
      id: 'lambda',
      type: NodeType.AWSLambda,
      label: 'Lambda Handler',
      zone: 'private',
      properties: { runtime: 'nodejs20', timeout: 29 },
    },
    {
      id: 'aurora',
      type: NodeType.AWSAurora,
      label: 'Aurora PostgreSQL',
      zone: 'data',
    },
  ],
  edges: [
    {
      id: 'e1',
      from: 'cloudfront',
      to: 'api-gateway',
      label: 'HTTPS',
      protocol: 'HTTPS',
      animated: true,
    },
    {
      id: 'e2',
      from: 'api-gateway',
      to: 'lambda',
      type: EdgeType.Invoke,
      label: 'invoke',
      animated: true,
    },
    {
      id: 'e3',
      from: 'lambda',
      to: 'aurora',
      type: EdgeType.Reads,
      label: 'SQL',
      protocol: 'PostgreSQL',
    },
  ],
  zones: [
    { id: 'public', label: 'Public Zone', type: ZoneType.Public, color: '#EFF6FF' },
    { id: 'private', label: 'Private Zone', type: ZoneType.Private, color: '#F0FDF4' },
    { id: 'data', label: 'Data Zone', type: ZoneType.Database, color: '#FEF3C7' },
  ],
};

const c4Context: GridIR = {
  version: '1.0',
  diagram_type: DiagramType.C4Context,
  abstraction_level: 1,
  title: 'System Context',
  nodes: [
    { id: 'user', type: NodeType.User, label: 'End User' },
    { id: 'admin', type: NodeType.User, label: 'Administrator' },
    { id: 'system', type: NodeType.System, label: 'ChiselGrid Platform' },
    { id: 'bedrock', type: NodeType.External, label: 'AWS Bedrock' },
  ],
  edges: [
    { id: 'e1', from: 'user', to: 'system', label: 'reads content' },
    { id: 'e2', from: 'admin', to: 'system', label: 'manages content' },
    { id: 'e3', from: 'system', to: 'bedrock', label: 'AI requests' },
  ],
};

const c4Container: GridIR = {
  version: '1.0',
  diagram_type: DiagramType.C4Container,
  abstraction_level: 2,
  title: 'Container Diagram',
  nodes: [
    { id: 'web', type: NodeType.Container, label: 'Next.js Web App' },
    { id: 'api', type: NodeType.Container, label: 'API Lambda' },
    { id: 'agents', type: NodeType.Container, label: 'Agent Workers' },
    { id: 'db', type: NodeType.Database, label: 'Aurora PostgreSQL' },
  ],
  edges: [
    { id: 'e1', from: 'web', to: 'api', label: 'HTTPS/JSON' },
    { id: 'e2', from: 'api', to: 'agents', type: EdgeType.Async, label: 'queue' },
    { id: 'e3', from: 'api', to: 'db', label: 'SQL' },
    { id: 'e4', from: 'agents', to: 'db', label: 'SQL' },
  ],
};

const c4Component: GridIR = {
  version: '1.0',
  diagram_type: DiagramType.C4Component,
  abstraction_level: 3,
  title: 'Component Diagram',
  nodes: [
    { id: 'controller', type: NodeType.Component, label: 'Request Controller' },
    { id: 'service', type: NodeType.Component, label: 'Business Service' },
    { id: 'repo', type: NodeType.Component, label: 'Repository' },
  ],
  edges: [
    { id: 'e1', from: 'controller', to: 'service', label: 'calls' },
    { id: 'e2', from: 'service', to: 'repo', label: 'uses' },
  ],
};

const sequence: GridIR = {
  version: '1.0',
  diagram_type: DiagramType.Sequence,
  title: 'Login Sequence',
  nodes: [
    { id: 'user', type: NodeType.Actor, label: 'User' },
    { id: 'web', type: NodeType.Service, label: 'Web App' },
    { id: 'cognito', type: NodeType.AWSCognito, label: 'Cognito' },
    { id: 'api', type: NodeType.AWSAPIGateway, label: 'API' },
  ],
  edges: [
    { id: 'e1', from: 'user', to: 'web', type: EdgeType.Request, label: 'enter credentials', order: 1 },
    { id: 'e2', from: 'web', to: 'cognito', type: EdgeType.Request, label: 'authenticate', order: 2 },
    { id: 'e3', from: 'cognito', to: 'web', type: EdgeType.Response, label: 'id token', order: 3 },
    { id: 'e4', from: 'web', to: 'api', type: EdgeType.Request, label: 'authorized request', order: 4 },
  ],
};

const flowchart: GridIR = {
  version: '1.0',
  diagram_type: DiagramType.Flowchart,
  title: 'Content Publish Flow',
  nodes: [
    { id: 'start', type: NodeType.Start, label: 'Start' },
    { id: 'draft', type: NodeType.Process, label: 'Create Draft' },
    { id: 'review', type: NodeType.Decision, label: 'Reviewed?' },
    { id: 'publish', type: NodeType.Process, label: 'Publish' },
    { id: 'end', type: NodeType.End, label: 'End' },
  ],
  edges: [
    { id: 'e1', from: 'start', to: 'draft' },
    { id: 'e2', from: 'draft', to: 'review' },
    { id: 'e3', from: 'review', to: 'publish', label: 'yes' },
    { id: 'e4', from: 'publish', to: 'end' },
  ],
};

const erDiagram: GridIR = {
  version: '1.0',
  diagram_type: DiagramType.ERDiagram,
  title: 'Content Data Model',
  nodes: [
    { id: 'tenant', type: NodeType.Entity, label: 'Tenant' },
    { id: 'user', type: NodeType.Entity, label: 'User' },
    { id: 'content', type: NodeType.Entity, label: 'Content' },
  ],
  edges: [
    { id: 'e1', from: 'tenant', to: 'user', type: EdgeType.Relates, label: '1 : N' },
    { id: 'e2', from: 'user', to: 'content', type: EdgeType.Relates, label: '1 : N' },
  ],
};

const networkTopology: GridIR = {
  version: '1.0',
  diagram_type: DiagramType.NetworkTopology,
  title: 'VPC Network Topology',
  nodes: [
    { id: 'internet', type: NodeType.External, label: 'Internet' },
    { id: 'public-subnet', type: NodeType.Service, label: 'Public Subnet', zone: 'public' },
    { id: 'private-subnet', type: NodeType.Service, label: 'Private Subnet', zone: 'private' },
    { id: 'db-subnet', type: NodeType.Database, label: 'DB Subnet', zone: 'data' },
  ],
  edges: [
    { id: 'e1', from: 'internet', to: 'public-subnet', label: 'IGW' },
    { id: 'e2', from: 'public-subnet', to: 'private-subnet', label: 'NAT' },
    { id: 'e3', from: 'private-subnet', to: 'db-subnet', label: 'TCP 5432' },
  ],
  zones: [
    { id: 'public', label: 'Public', type: ZoneType.Public },
    { id: 'private', label: 'Private', type: ZoneType.Private },
    { id: 'data', label: 'Data', type: ZoneType.Database },
  ],
};

const timeline: GridIR = {
  version: '1.0',
  diagram_type: DiagramType.Timeline,
  title: 'Platform Roadmap',
  nodes: [
    { id: 'm1', type: NodeType.Process, label: 'Foundation' },
    { id: 'm2', type: NodeType.Process, label: 'Grid MVP' },
    { id: 'm3', type: NodeType.Process, label: 'Animation' },
    { id: 'm4', type: NodeType.Process, label: 'Fine-tuning' },
  ],
  edges: [
    { id: 'e1', from: 'm1', to: 'm2', label: 'April 2026' },
    { id: 'e2', from: 'm2', to: 'm3', label: 'May 2026' },
    { id: 'e3', from: 'm3', to: 'm4', label: 'September 2026' },
  ],
};

const spatial3D: GridIR = {
  version: '1.0',
  diagram_type: DiagramType.Spatial3D,
  title: '3D Spatial Architecture',
  nodes: [
    { id: 'frontend', type: NodeType.Container, label: 'Frontend Layer', position: { x: 0, y: 0 } },
    { id: 'backend', type: NodeType.Container, label: 'Backend Layer', position: { x: 0, y: 100 } },
    { id: 'data', type: NodeType.Database, label: 'Data Layer', position: { x: 0, y: 200 } },
  ],
  edges: [
    { id: 'e1', from: 'frontend', to: 'backend' },
    { id: 'e2', from: 'backend', to: 'data' },
  ],
};

const awsPaymentServerless: GridIR = {
  version: '1.0',
  diagram_type: DiagramType.AWSArchitecture,
  abstraction_level: 2,
  title: 'Serverless Payment API',
  description:
    'Reference architecture for a Philippine digital bank payment API with PCI-DSS compliance, ' +
    'InstaPay integration and BSP reporting.',
  nodes: [
    {
      id: 'bank-customer',
      type: 'external.user',
      label: 'Bank Customer',
      zone: 'external',
      position: { x: 50, y: 350 },
    },
    {
      id: 'waf',
      type: 'aws.waf',
      label: 'WAF',
      zone: 'public',
      properties: { rules: 'AWS Managed', ddos: true },
      position: { x: 200, y: 300 },
    },
    {
      id: 'cloudfront',
      type: NodeType.AWSCloudFront,
      label: 'CloudFront',
      zone: 'public',
      position: { x: 380, y: 300 },
    },
    {
      id: 'api-gateway',
      type: NodeType.AWSAPIGateway,
      label: 'API Gateway',
      zone: 'public',
      properties: { protocol: 'REST', auth: 'Cognito' },
      position: { x: 560, y: 300 },
    },
    {
      id: 'cognito',
      type: NodeType.AWSCognito,
      label: 'Cognito',
      zone: 'public',
      position: { x: 560, y: 100 },
    },
    {
      id: 'auth-lambda',
      type: NodeType.AWSLambda,
      label: 'Auth Lambda',
      zone: 'private',
      properties: { runtime: 'nodejs20', timeout: 10 },
      position: { x: 750, y: 150 },
    },
    {
      id: 'payment-api-lambda',
      type: NodeType.AWSLambda,
      label: 'Payment API Lambda',
      zone: 'private',
      properties: { runtime: 'nodejs20', timeout: 29 },
      position: { x: 750, y: 300 },
    },
    {
      id: 'document-handler-lambda',
      type: NodeType.AWSLambda,
      label: 'Document Handler',
      zone: 'private',
      properties: { runtime: 'nodejs20', timeout: 29 },
      position: { x: 750, y: 500 },
    },
    {
      id: 'dlq',
      type: NodeType.AWSSQS,
      label: 'DLQ',
      zone: 'private',
      properties: { purpose: 'dead-letter-queue' },
      position: { x: 960, y: 170 },
    },
    {
      id: 'sqs-payment',
      type: NodeType.AWSSQS,
      label: 'SQS Payment Queue',
      zone: 'private',
      properties: { fifo: true },
      position: { x: 960, y: 250 },
    },
    {
      id: 'payment-processor-lambda',
      type: NodeType.AWSLambda,
      label: 'Payment Processor Lambda',
      zone: 'compliance',
      properties: { runtime: 'nodejs20', timeout: 60 },
      position: { x: 960, y: 350 },
    },
    {
      id: 's3-documents',
      type: NodeType.AWSS3,
      label: 'S3 Document Storage',
      zone: 'private',
      properties: { encryption: 'SSE-KMS', versioning: true },
      position: { x: 960, y: 550 },
    },
    {
      id: 'cloudwatch',
      type: 'aws.cloudwatch',
      label: 'CloudWatch',
      zone: 'data',
      position: { x: 960, y: 680 },
    },
    {
      id: 'aurora-primary',
      type: NodeType.AWSAurora,
      label: 'Aurora Primary',
      zone: 'compliance',
      properties: { engine: 'postgres', encrypted: true },
      position: { x: 1180, y: 250 },
    },
    {
      id: 'aurora-replica',
      type: NodeType.AWSAurora,
      label: 'Aurora Replica',
      zone: 'compliance',
      properties: { role: 'read-replica' },
      position: { x: 1180, y: 370 },
    },
    {
      id: 'secrets-manager',
      type: NodeType.AWSSecretsManager,
      label: 'Secrets Manager',
      zone: 'compliance',
      position: { x: 1180, y: 490 },
    },
    {
      id: 'kms',
      type: 'aws.kms',
      label: 'KMS',
      zone: 'data',
      position: { x: 1180, y: 610 },
    },
    {
      id: 'cloudtrail',
      type: 'aws.cloudtrail',
      label: 'CloudTrail',
      zone: 'data',
      position: { x: 1180, y: 730 },
    },
    {
      id: 'instapay',
      type: 'external.payment_network',
      label: 'InstaPay Switch',
      zone: 'external',
      position: { x: 1400, y: 300 },
    },
    {
      id: 'bsp-reporting',
      type: 'external.system',
      label: 'BSP Reporting',
      zone: 'external',
      position: { x: 1400, y: 450 },
    },
  ],
  edges: [
    {
      id: 'e1',
      from: 'bank-customer',
      to: 'waf',
      type: EdgeType.Request,
      label: 'HTTPS',
      protocol: 'HTTPS',
    },
    {
      id: 'e2',
      from: 'waf',
      to: 'cloudfront',
      type: EdgeType.Request,
      label: 'filtered',
      protocol: 'HTTPS',
    },
    {
      id: 'e3',
      from: 'cloudfront',
      to: 'api-gateway',
      type: EdgeType.Request,
      label: 'HTTPS',
      protocol: 'HTTPS',
      animated: true,
    },
    {
      id: 'e4',
      from: 'api-gateway',
      to: 'cognito',
      type: EdgeType.Request,
      label: 'authorize',
      protocol: 'HTTPS',
    },
    {
      id: 'e5',
      from: 'api-gateway',
      to: 'auth-lambda',
      type: EdgeType.Invoke,
      label: 'invoke',
      protocol: 'HTTPS',
    },
    {
      id: 'e6',
      from: 'api-gateway',
      to: 'payment-api-lambda',
      type: EdgeType.Invoke,
      label: 'invoke',
      protocol: 'HTTPS',
      animated: true,
    },
    {
      id: 'e7',
      from: 'api-gateway',
      to: 'document-handler-lambda',
      type: EdgeType.Invoke,
      label: 'invoke',
      protocol: 'HTTPS',
    },
    {
      id: 'e8',
      from: 'payment-api-lambda',
      to: 'sqs-payment',
      type: EdgeType.Publishes,
      label: 'enqueue',
      protocol: 'SQS',
    },
    {
      id: 'e9',
      from: 'sqs-payment',
      to: 'payment-processor-lambda',
      type: EdgeType.Subscribes,
      label: 'consume',
      protocol: 'SQS',
      animated: true,
    },
    {
      id: 'e10',
      from: 'sqs-payment',
      to: 'dlq',
      type: EdgeType.Async,
      label: 'failed',
      protocol: 'SQS',
    },
    {
      id: 'e11',
      from: 'payment-processor-lambda',
      to: 'aurora-primary',
      type: EdgeType.Writes,
      label: 'SQL',
      protocol: 'PostgreSQL',
      animated: true,
    },
    {
      id: 'e12',
      from: 'aurora-primary',
      to: 'aurora-replica',
      type: EdgeType.DataFlow,
      label: 'replication',
      protocol: 'PostgreSQL',
    },
    {
      id: 'e13',
      from: 'payment-processor-lambda',
      to: 'secrets-manager',
      type: EdgeType.Reads,
      label: 'get secret',
      protocol: 'HTTPS',
    },
    {
      id: 'e14',
      from: 'secrets-manager',
      to: 'kms',
      type: EdgeType.Uses,
      label: 'decrypt',
      protocol: 'KMS',
    },
    {
      id: 'e15',
      from: 'document-handler-lambda',
      to: 's3-documents',
      type: EdgeType.Writes,
      label: 'put object',
      protocol: 'HTTPS',
    },
    {
      id: 'e16',
      from: 's3-documents',
      to: 'kms',
      type: EdgeType.Uses,
      label: 'SSE-KMS',
      protocol: 'KMS',
    },
    {
      id: 'e17',
      from: 'payment-processor-lambda',
      to: 'instapay',
      type: EdgeType.Request,
      label: 'settle',
      protocol: 'HTTPS',
    },
    {
      id: 'e18',
      from: 'payment-processor-lambda',
      to: 'bsp-reporting',
      type: EdgeType.Publishes,
      label: 'report',
      protocol: 'HTTPS',
    },
    {
      id: 'e19',
      from: 'payment-processor-lambda',
      to: 'cloudwatch',
      type: EdgeType.Publishes,
      label: 'logs/metrics',
    },
    {
      id: 'e20',
      from: 'cloudwatch',
      to: 'cloudtrail',
      type: EdgeType.DataFlow,
      label: 'audit',
    },
  ],
  zones: [
    { id: 'public', label: 'Public Zone', type: ZoneType.Public, color: '#EFF6FF' },
    { id: 'private', label: 'Private Zone', type: ZoneType.Private, color: '#F0FDF4' },
    { id: 'compliance', label: 'PCI-DSS Zone', type: ZoneType.Compliance, color: '#FEF2F2' },
    { id: 'data', label: 'Data / Audit Zone', type: ZoneType.Database, color: '#FEF3C7' },
    { id: 'external', label: 'External Systems', type: ZoneType.External, color: '#F1F5F9' },
  ],
  annotations: [
    {
      node: 'payment-processor-lambda',
      type: 'compliance',
      text: 'PCI-DSS Zone 1 — cardholder data processing',
    },
    {
      node: 'aurora-primary',
      type: 'compliance',
      text: 'Encrypted at rest (KMS). PII residency: ap-southeast-1.',
    },
  ],
};

const c4ContextBanking: GridIR = {
  version: '1.0',
  diagram_type: DiagramType.C4Context,
  abstraction_level: 1,
  title: 'Digital Bank — System Context',
  description: 'C4 Level 1 context for a Philippine digital bank.',
  nodes: [
    {
      id: 'bank-customer',
      type: 'external.user',
      label: 'Bank Customer',
      position: { x: 100, y: 300 },
    },
    {
      id: 'mobile-app',
      type: 'external.system',
      label: 'Mobile App',
      position: { x: 320, y: 300 },
    },
    {
      id: 'digital-banking',
      type: NodeType.System,
      label: 'Digital Banking System',
      zone: 'system',
      position: { x: 560, y: 300 },
    },
    {
      id: 'core-banking',
      type: 'external.system',
      label: 'Core Banking System',
      properties: { note: 'legacy' },
      position: { x: 820, y: 100 },
    },
    {
      id: 'bsp-reporting',
      type: 'external.system',
      label: 'BSP Reporting',
      position: { x: 820, y: 260 },
    },
    {
      id: 'instapay',
      type: 'external.payment_network',
      label: 'InstaPay Switch',
      position: { x: 820, y: 420 },
    },
    {
      id: 'card-network',
      type: 'external.payment_network',
      label: 'Card Network',
      position: { x: 820, y: 560 },
    },
  ],
  edges: [
    { id: 'e1', from: 'bank-customer', to: 'mobile-app', label: 'uses' },
    { id: 'e2', from: 'mobile-app', to: 'digital-banking', label: 'API' },
    { id: 'e3', from: 'digital-banking', to: 'core-banking', label: 'accounts / ledger' },
    { id: 'e4', from: 'digital-banking', to: 'bsp-reporting', label: 'regulatory reports' },
    { id: 'e5', from: 'digital-banking', to: 'instapay', label: 'payment settlement' },
    { id: 'e6', from: 'digital-banking', to: 'card-network', label: 'card auth' },
  ],
  zones: [
    { id: 'system', label: 'Digital Bank', type: ZoneType.Internal, color: '#EFF6FF' },
  ],
};

const awsMicroservices: GridIR = {
  version: '1.0',
  diagram_type: DiagramType.AWSArchitecture,
  abstraction_level: 2,
  title: 'AWS Microservices',
  description: 'Reference microservices architecture on AWS with per-service Aurora databases.',
  nodes: [
    {
      id: 'cloudfront',
      type: NodeType.AWSCloudFront,
      label: 'CloudFront',
      zone: 'public',
      position: { x: 100, y: 300 },
    },
    {
      id: 'cognito',
      type: NodeType.AWSCognito,
      label: 'Cognito',
      zone: 'public',
      position: { x: 300, y: 100 },
    },
    {
      id: 'api-gateway',
      type: NodeType.AWSAPIGateway,
      label: 'API Gateway',
      zone: 'public',
      properties: { protocol: 'REST', auth: 'Cognito' },
      position: { x: 300, y: 300 },
    },
    {
      id: 'redis',
      type: 'aws.elasticache',
      label: 'Redis ElastiCache',
      zone: 'private',
      properties: { purpose: 'session' },
      position: { x: 300, y: 500 },
    },
    {
      id: 'auth-lambda',
      type: NodeType.AWSLambda,
      label: 'Auth Service',
      zone: 'private',
      properties: { runtime: 'nodejs20' },
      position: { x: 560, y: 150 },
    },
    {
      id: 'orders-lambda',
      type: NodeType.AWSLambda,
      label: 'Orders Service',
      zone: 'private',
      properties: { runtime: 'nodejs20' },
      position: { x: 560, y: 300 },
    },
    {
      id: 'products-lambda',
      type: NodeType.AWSLambda,
      label: 'Products Service',
      zone: 'private',
      properties: { runtime: 'nodejs20' },
      position: { x: 560, y: 450 },
    },
    {
      id: 'sqs-events',
      type: NodeType.AWSSQS,
      label: 'SQS Events',
      zone: 'private',
      position: { x: 560, y: 600 },
    },
    {
      id: 'auth-db',
      type: NodeType.AWSAurora,
      label: 'Auth DB',
      zone: 'data',
      position: { x: 820, y: 150 },
    },
    {
      id: 'orders-db',
      type: NodeType.AWSAurora,
      label: 'Orders DB',
      zone: 'data',
      position: { x: 820, y: 300 },
    },
    {
      id: 'products-db',
      type: NodeType.AWSAurora,
      label: 'Products DB',
      zone: 'data',
      position: { x: 820, y: 450 },
    },
  ],
  edges: [
    { id: 'e1', from: 'cloudfront', to: 'api-gateway', label: 'HTTPS', protocol: 'HTTPS', animated: true },
    { id: 'e2', from: 'api-gateway', to: 'cognito', label: 'authorize' },
    { id: 'e3', from: 'api-gateway', to: 'auth-lambda', type: EdgeType.Invoke, label: 'invoke', animated: true },
    { id: 'e4', from: 'api-gateway', to: 'orders-lambda', type: EdgeType.Invoke, label: 'invoke', animated: true },
    { id: 'e5', from: 'api-gateway', to: 'products-lambda', type: EdgeType.Invoke, label: 'invoke', animated: true },
    { id: 'e6', from: 'auth-lambda', to: 'redis', type: EdgeType.Reads, label: 'session' },
    { id: 'e7', from: 'auth-lambda', to: 'auth-db', type: EdgeType.Writes, label: 'SQL', protocol: 'PostgreSQL' },
    { id: 'e8', from: 'orders-lambda', to: 'orders-db', type: EdgeType.Writes, label: 'SQL', protocol: 'PostgreSQL' },
    { id: 'e9', from: 'products-lambda', to: 'products-db', type: EdgeType.Writes, label: 'SQL', protocol: 'PostgreSQL' },
    { id: 'e10', from: 'orders-lambda', to: 'sqs-events', type: EdgeType.Publishes, label: 'order.created' },
    { id: 'e11', from: 'sqs-events', to: 'products-lambda', type: EdgeType.Subscribes, label: 'inventory update' },
  ],
  zones: [
    { id: 'public', label: 'Public Zone', type: ZoneType.Public, color: '#EFF6FF' },
    { id: 'private', label: 'Private Zone', type: ZoneType.Private, color: '#F0FDF4' },
    { id: 'data', label: 'Data Zone', type: ZoneType.Database, color: '#FEF3C7' },
  ],
};

export const TEMPLATES: Record<string, GridIR> = {
  [DiagramType.AWSArchitecture]: awsArchitecture,
  [DiagramType.C4Context]: c4Context,
  [DiagramType.C4Container]: c4Container,
  [DiagramType.C4Component]: c4Component,
  [DiagramType.Sequence]: sequence,
  [DiagramType.Flowchart]: flowchart,
  [DiagramType.ERDiagram]: erDiagram,
  [DiagramType.NetworkTopology]: networkTopology,
  [DiagramType.Timeline]: timeline,
  [DiagramType.Spatial3D]: spatial3D,
  aws_payment_serverless: awsPaymentServerless,
  c4_context_banking: c4ContextBanking,
  aws_microservices: awsMicroservices,
};
